import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../app/components/header";
import LeftNav from "../app/components/left-nav";
import clsx from "clsx";
import Player from "./components/player";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const show = isMoblie();
  return (
    <html lang="en">
      <body className={clsx(`${ inter.className }` ,{})}>
        <Header />
        <div className="w-full">
          {
            // show ? <LeftNav/> :<></>
          }
          <LeftNav/>
          {children}
          <Player/>
        </div>
      </body>
    </html>
  );
}
